# --!Ups

<<<<<<< HEAD
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav001',1,'Raymond','Galligan','Goalkeeper','Lacken',32,5,0,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav002',2,'Fergal','Reilly','Defender','Castlerahan',24,5,0,1,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav003',3,'Padraig','Faulkner','Defender','Kingscourt',29,5,0,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav004',4,'Killian','Brady','Defender','Mullahoran',27,4,0,1,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav005',5,'Martin','Reilly','Defender','Killygarry',30,5,6,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav006',6,'Ciaran','Brady','Defender','Arvagh',32,5,0,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav007',7,'Gerard','Smith','Defender','Lavey',29,5,7,1,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav008',8,'Killian','Clarke','Midfield','Shercock',26,5,1,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav009',9,'Tomas','Corr','Midfield','Denn',29,5,3,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav010',10,'Michael','Argue','Forward','Bailieborough',25,5,2,2,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav011',11,'Dara','McVeety','Forward','Crosserlough',28,5,7,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav012',12,'Conor','Madden','Forward','Gowna',20,5,7,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav013',13,'Niall','Clerkin','Forward','Shercock',29,5,5,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav014',14,'Gearoid','McKiernan','Forward','Swanlinbad',31,5,6,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav015',15,'Sean','Johnston','Forward','Cavan Gaels',25,5,7,1,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav016',16,'James','Farrelly','Goalkeeper','Kingscourt',21,0,0,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav017',17,'Jason','McLoughlin','Defender','Shannon Gaels',23,1,0,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav018',18,'Stephen','Murray','Defender','Cavan Gaels',21,1,0,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav019',19,'Conor','Moynagh','Defender','Drumgoon',19,0,0,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav020',20,'Rory','Dunne','Defender','Redhills',32,0,0,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav021',21,'Niall','Murray','Midfield','Cavan Gaels',29,2,0,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav022',22,'Joe','Dillon','Midfield','Kingscourt',30,2,0,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav023',23,'Paul','OConnor','Forward','Cavan Gaels',23,0,0,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav024',24,'Cian','Mackey','Forward','Castlerahan',21,1,3,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav025',25,'Niall','McDermott','Forward','Ballinagh',31,0,0,0,0,0,'gaa09' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'cav026',26,'John','McCutcheon','Forward','Cootehill Celtic',27,0,0,0,0,0,'gaa09' );

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub001',1,'Stephen','Cluxton','Goalkeeper','Parnells',35,5,2,1,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub002',2,'Philip','McMahon','Defender','Ballymun Kickhams',25,5,0,1,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub003',3,'Michael','Fitzsimons','Defender','Cuala',26,5,0,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub004',4,'David','Byrne','Defender','Naomh Ólaf',27,5,0,0,1,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub005',5,'Darren','Daly','Defender','Fingal Ravens',22,5,2,1,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub006',6,'John','Small','Defender','Ballymun Kickhams',25,5,1,0,1,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub007',7,'Eric','Lowndes','Defender','St. Peregrines',21,5,1,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub008',8,'Brian','Fenton','Midfield','Raheny',29,5,3,1,0,1,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub009',9,'Michael Darragh','MacAuley','Midfield','Ballyboden St. Endas',30,5,1,0,1,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub010',10,'Niall','Scully','Forward','Templeogue Synge Street',24,5,9,1,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub011',11,'Dean','Rock','Forward','Ballymun Kickhams',26,5,12,1,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub012',12,'Shane','Carthy','Forward','St Vincents',23,5,10,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub013',13,'Ciarán','Kilkenny','Forward','Castleknock',24,5,8,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub014',14,'Eoghan','OGara','Forward','Templeogue Synge Street',27,5,11,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub015',15,'Conor','McHugh','Forward','Na Fianna',22,5,6,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub016',16,'Evan','Comerford','Goalkeeper','Ballymun Kickhams',28,0,0,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub017',17,'Colm','Basquel','Defender','Ballyboden St. Endas',27,2,0,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub018',18,'Shane','Carthy','Defender','Naomh Mearnóg',24,4,0,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub019',19,'Paul','Flynn','Defender','Fingallians',25,3,0,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub020',20,'Robbie','McDaid','Defender','Ballyboden St. Endas',23,0,0,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub021',21,'Kevin','McManamon','Midfield','St Judes',24,4,1,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub022',22,'Conor','Mullally','Midfield','Cuala',30,0,0,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub023',23,'Eoin','OBrien','Forward','Castleknock',31,1,0,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub024',24,'Emmett','ÓConghaile','Forward','Lucan Sarsfields',21,3,2,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub025',25,'Ciarán','Reddin','Forward','Naomh Maur',19,0,0,0,0,0,'gaa19' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ( 'dub026',26,'Jack','Smith','Forward','Skerries Harps',23,3,2,0,0,0,'gaa19' );

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker001',1,'Brendan','Kealy','Goalkeeper','Kilcummin',28,5,0,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker002',2,'Shane','Enright','Defender','Tarbert',23,5,5,2,1,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker003',3,'Killian','Young','Defender','Renard',27,4,0,1,0,1,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker004',4,'Ronan','Shanahan','Defender','Austin Stacks',31,5,3,1,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker005',5,'Peter','Crowley','Defender','Laune Rangers',22,4,0,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker006',6,'Tadhg','Morley','Defender','Templenoe',29,5,3,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker007',7,'Paul','Murphy','Defender','Rathmore',26,5,7,2,0,1,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker008',8,'David','Moran','Midfield','Kerins ORahillys',32,5,7,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker009',9,'Jack','Barry','Midfield','Na Gaeil',30,5,4,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker010',10,'Kevin','McCarthy','Forward','Kilcummin',28,5,5,1,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker011',11,'Jack','Savage','Forward','Kerins ORahillys',25,5,12,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker012',12,'Donnchadh','Walsh','Forward','Cromane',23,4,8,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker013',13,'Barry','John Keane','Forward','Kerins ORahillys',24,5,15,1,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker014',14,'Paul','Geaney','Forward','Dingle',25,4,18,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker015',15,'James','ODonoghue','Forward','Legion',23,5,13,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker016',16,'Brian','Kelly','Goalkeeper','Legion',29,0,0,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker017',17,'Jonathan','Lyne','Defender','Legion',21,1,0,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker018',18,'Mark','Griffin','Defender','St. Michaels Foilmore',23,3,0,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker019',19,'Anthony','Maher','Defender','Duagh',32,1,0,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker020',20,'Stephen','OBrien','Defender','Kenmare Shamrocks',30,0,0,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker021',21,'Darran','OSullivan','Midfield','Glenbeigh Glencar',23,1,0,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker022',22,'Michael','Geaney','Midfield','Dingle',26,0,0,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker023',23,'Cathal','ÓLúing','Forward','An Ghaeltacht',31,0,0,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker024',24,'Gavin','Crowley','Forward','Templenoe',28,2,6,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker025',25,'Denis','Daly','Forward','St. Marys',26,0,0,0,0,0,'gaa32' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ker026',26,'Conor','Keane','Forward','Legion',28,2,2,0,0,0,'gaa32' );

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may001',1,'David','Clarke','Goalkeeper','Ballina Stephenites',23,5,0,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may002',2,'Donie','Newcombe','Defender','Castlebar Mitchels',29,5,0,2,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may003',3,'Keith','Higgins','Defender','Ballyhaunis',26,5,0,1,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may004',4,'Patrick','Durcan','Defender','Castlebar Mitchels',24,5,0,1,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may005',5,'Colm','Boyle','Defender','Davitts',23,5,2,1,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may006',6,'Stephen','Coen','Defender','Hollymount Carramore',29,5,3,2,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may007',7,'David','Drake','Defender','Ballaghadereen',21,5,1,2,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may008',8,'Donal','Vaughan','Midfield','Ballinrobe',30,5,3,2,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may009',9,'Jason','Gibbons','Midfield','Ballintubber',26,5,1,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may010',10,'Fergal','Boland','Forward','Aghamore',28,5,6,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may011',11,'Kevin','McLoughlin','Forward','Knockmore',21,5,9,1,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may012',12,'Diarmuid','OConnor','Forward','Ballintubber',18,5,14,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may013',13,'Evan','Regan','Forward','Ballina Stephenites',27,5,6,1,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may014',14,'Cillian','OConnor','Forward','Ballintubber',26,5,16,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may015',15,'Andy','Moran','Forward','Ballaghadereen',31,5,5,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may016',16,'Rob','Hennelly','Goalkeeper','Breaffy',21,1,0,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may017',17,'Brendan','Harrison','Defender','Aghamore',28,2,0,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may018',18,'Caolán','Crowe','Defender','Garrymore',27,1,0,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may019',19,'Michael','Plunkett','Defender','Ballintubber',22,3,0,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may020',20,'Eoghan','OReilly','Defender','Castlebar Mitchels',23,1,0,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may021',21,'Lee','Keegan','Midfield','Westport',32,4,0,2,0,1,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may022',22,'Shane','Nally','Midfield','Garrymore',29,0,0,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may023',23,'Conor','Loftus','Forward','Crossmolina Deel Rovers',23,0,0,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may024',24,'Conor','OShea','Forward','Breaffy',28,2,3,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may025',25,'Liam','Irwin','Forward','Breaffy',24,2,3,0,0,0,'gaa12');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('may026',26,'Tom','Parsons','Forward','Charlestown Sarsfields',23,5,5,0,0,0,'gaa12');

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr001',1,'Michael','ONeill','Goalkeeper','Clonoe',23,5,0,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr002',2,'Pádraig','Hampsey','Defender','Coalisland',24,4,7,1,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr003',3,'Ronan','McNamee','Defender','Aghyaran',25,5,0,2,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr004',4,'Cathal','McCarron','Defender','Dromore',26,5,2,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr005',5,'Tiernan','McCann','Defender','Killyclogher',29,5,2,1,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr006',6,'Mattie','Donnelly','Defender','Trillick',30,5,2,2,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr007',7,'Jonathan','Monroe','Defender','Carrickmore',32,4,0,1,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr008',8,'Colm','Cavanagh','Midfield','Moy',33,5,5,2,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr009',9,'Pádraig','McNulty','Midfield','Dungannon',24,5,1,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr010',10,'Conor','Meyler','Forward','Omagh',22,4,2,1,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr011',11,'Niall','Sludden','Forward','Dromore',23,5,6,0,1,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr012',12,'Peter','Harte','Forward','Errigal Ciarán',25,5,12,1,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr013',13,'Darren','McCurry','Forward','Edendork',27,5,15,1,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr014',14,'Cathal','McShane','Forward','Owen Roe ONeills',29,4,3,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr015',15,'Ronan','ONeill','Forward','Omagh',27,5,10,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr016',16,'Niall','Morgan','Goalkeeper','Edendork',25,0,0,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr017',17,'Mark','Bradley','Defender','Killyclogher',21,2,0,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr018',18,'Lee','Brennan','Defender','Trillick',23,1,0,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr019',19,'Seán','Cavanagh','Defender','Moy',27,2,0,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr020',20,'Conall','McCann','Defender','Killyclogher',29,0,0,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr021',21,'Declan','McClure','Midfield','Clonoe',21,0,0,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr022',22,'Cahir','McCullagh','Midfield','Greencastle',31,1,0,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr023',23,'Aidan','McCrory','Forward','Errigal Ciarán',30,2,0,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr024',24,'Ronan','McHugh','Forward','Aghyaran',27,1,0,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr025',25,'Justin','McMahon','Forward','Omagh',22,2,0,0,0,0,'gaa02');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('tyr026',26,'David','Mulgrew','Forward','Ardboe',29,0,0,0,0,0,'gaa02');

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don001',1,'Mark Anthony','McGinley','Goalkeeper','St. Michaels',26,5,0,1,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don002',2,'Paddy','McGrath','Defender','Ardara',23,5,1,1,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don003',3,'Neil','McGee','Defender','Ghaoth Dobhair',26,5,1,1,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don004',4,'Eamon','McGee','Defender','Ghaoth Dobhair',27,5,0,1,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don005',5,'Ryan','McHugh','Defender','Kilcar',29,5,2,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don006',6,'Karl','Lacey','Defender','The Four Masters',23,5,1,2,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don007',7,'Frank','McGlynn','Defender','Glenfin',21,5,3,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don008',8,'Rory','Kavanagh','Midfield','St. Eunans',24,5,1,1,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don009',9,'Odhrán','MacNiallais','Midfield','Ghaoth Dobhair',29,5,2,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don010',10,'Anthony','Thompson','Forward','Naomh Conaill',25,5,5,0,1,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don011',11,'Martin','McElhinney','Forward','St. Michaels',28,5,7,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don012',12,'Eoin','McHugh','Forward','Kilcar',31,5,2,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don013',13,'Patrick','McBrearty','Forward','Kilcar',23,5,15,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don014',14,'Michael','Murphy','Forward','Glenswilly',27,5,12,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don015',15,'Martin','OReilly','Forward','Seán MacCumhaills',25,5,10,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don016',16,'Peter','Boyle','Goalkeeper','Aodh Ruadh',34,1,0,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don017',17,'Ciarán','Gillespie','Defender','Ghaoth Dobhair',22,2,1,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don018',18,'Leo','McLoone','Defender','Naomh Conaill',26,2,0,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don019',19,'Christy','Toye','Defender','St. Michaels',25,1,0,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don020',20,'Colm','McFadden','Defender','St. Michaels',36,4,7,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don021',21,'Hugh','McFadden','Midfield','Killybegs',19,1,2,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don022',22,'Mark','McHugh','Midfield','Kilcar',25,1,1,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don023',23,'Eamonn','Doherty','Forward','St. Eunans',29,2,0,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don024',24,'Ciarán','Thompson','Forward','Naomh Conaill',26,1,0,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don025',25,'Eoghan','Bán Gallagher','Forward','Killybegs',28,3,0,0,0,0,'gaa01');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('don026',26,'Michael','Carroll','Forward','Ghaoth Dobhair',19,0,0,0,0,0,'gaa01');

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon001',1,'Rory','Beggan','Goalkeeper','Scotstown',30,5,0,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon002',2,'Fintan','Kelly','Defender','Clones',27,5,1,1,1,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon003',3,'Drew','Wylie','Defender','Ballybay',22,5,1,2,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon004',4,'Ryan','Wylie','Defender','Ballybay',25,4,1,1,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon005',5,'Colin','Walshe','Defender','Doohamlet',29,4,3,1,0,1,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon006',6,'Neil','Mc Adam','Defender','Monaghan Harps',31,5,5,2,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon007',7,'Kieran','Duffy','Defender','Latton',33,5,5,1,1,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon008',8,'Darren','Hughes','Midfield','Scotstown',22,5,3,1,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon009',9,'Kieran','Hughes','Midfield','Scotstown',25,4,2,1,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon010',10,'Karl','OConnell','Forward','Tyholland',29,5,4,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon011',11,'Shane','Carey','Forward','Scotstown',23,4,6,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon012',12,'Gavin','Doogan','Forward','Magheracloone Mitchells',33,5,3,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon013',13,'Conor','McCarthy','Forward','Scotstown',28,5,5,1,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon014',14,'Thomas','Kerr','Forward','Ballybay',26,5,7,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon015',15,'Conor','McManus','Forward','Clontibret',29,5,16,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon016',16,'Conor','Forde','Goalkeeper','Scotstown',24,0,0,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon017',17,'James','Mealiff','Defender','Clones',30,2,2,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon018',18,'Owen','Coyle','Defender','Latton',21,1,0,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon019',19,'Brian','Greenan','Defender','Clontibret',23,1,0,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon020',20,'Mikey','Murnaghan','Defender','Donaghmoyne',28,1,0,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon021',21,'Niall','Kearns','Midfield','Sean McDermotts',31,0,0,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon022',22,'Dermot','Malone','Midfield','Castleblayney Faughs',27,0,0,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon023',23,'Owen','Duffy','Forward','Latton',24,1,0,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon024',24,'Ryan','McAnespie','Forward','Emyvale',28,2,2,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon025',25,'Stephen','Finnegan','Forward','Donaghmoyne',19,0,0,0,0,0,'gaa07');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('mon026',26,'Barry','McGinn','Forward','Doohamlet',21,2,1,0,0,0,'gaa07');

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros001',1,'Darren','OMalley','Goalkeeper','Michael Glaveys',28,5,0,1,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros002',2,'David','Murray','Defender','Pádraig Pearses',24,5,0,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros003',3,'Seán','Mullooly','Defender','Strokestown',28,5,1,4,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros004',4,'Niall','McInerney','Defender','St. Brigids',27,5,1,1,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros005',5,'John','McManus','Defender','Roscommon Gaels',23,5,3,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros006',6,'Seán','McDermott','Defender','Western Gaels',27,5,4,1,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros007',7,'Conor','Devaney','Defender','Kilbride',22,5,3,0,1,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros008',8,'Enda','Smith','Midfield','Boyle',29,5,2,0,0,1,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros009',9,'Tadhg','ORourke','Midfield','Tulsk',27,5,3,1,0,0,'gaa13' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros010',10,'Fintan','Cregg','Forward','Elphin',25,5,9,1,1,0,'gaa13' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros011',11,'Ronan','Stack','Forward','St. Brigids',32,5,6,1,0,0,'gaa13' );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros012',12,'Shane','Killoran','Forward','Elphin',21,5,10,1,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros013',13,'Donie','Smith','Forward','Boyle',18,5,11,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros014',14,'Ciaráin','Murtagh','Forward','St. Faithleachs',27,5,13,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros015',15,'Cian','Connolly','Forward','Roscommon Gaels',23,5,6,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros016',16,'Colm','Lavin','Goalkeeper','Éire Óg',30,0,0,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros017',17,'Paddy','Brogan','Defender','Strokestown',18,1,0,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros018',18,'Ciarán','Cafferkey','Defender','Western Gaels',19,2,0,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros019',19,'Thomas','Corcoran','Defender','Strokestown',28,1,0,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros020',20,'Thomas','Featherston','Defender','Oran',23,2,0,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros021',21,'Niall','Kilroy','Midfield','Fuerty',27,2,0,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros022',22,'Fergal','Lennon','Midfield','Clann na nGael',29,2,1,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros023',23,'Brian','Murtagh','Forward','St. Faithleachs',27,2,0,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros024',24,'Diarmuid','Murtagh','Forward','St. Faithleachs',23,3,0,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros025',25,'Gary','Patterson','Forward','Michael Glaveys',28,1,0,0,0,0,'gaa13');
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds,tid) values ('ros026',26,'Brian','Stack','Forward','St. Brigids',21,4,0,0,0,0,'gaa13');
=======
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav001',1,'Raymond','Galligan','Goalkeeper','Lacken',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav002',2,'Fergal','Reilly','Defender','Castlerahan',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav003',3,'Padraig','Faulkner','Defender','Kingscourt',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav004',4,'Killian','Brady','Defender','Mullahoran',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav005',5,'Martin','Reilly','Defender','Killygarry',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav006',6,'Ciaran','Brady','Defender','Arvagh',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav007',7,'Gerard','Smith','Defender','Lavey',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav008',8,'Killian','Clarke','Midfield','Shercock',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav009',9,'Tomas','Corr','Midfield','Denn',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav010',10,'Michael','Argue','Forward','Bailieborough',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav011',11,'Dara','McVeety','Forward','Crosserlough',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav012',12,'Conor','Madden','Forward','Gowna',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav013',13,'Niall','Clerkin','Forward','Shercock',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav014',14,'Gearoid','McKiernan','Forward','Swanlinbad',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav015',15,'Sean','Johnston','Forward','Cavan Gaels',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav016',16,'James','Farrelly','Goalkeeper','Kingscourt',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav017',17,'Jason','McLoughlin','Defender','Shannon Gaels',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav018',18,'Stephen','Murray','Defender','Cavan Gaels',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav019',19,'Conor','Moynagh','Defender','Drumgoon',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav020',20,'Rory','Dunne','Defender','Redhills',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav021',21,'Niall','Murray','Midfield','Cavan Gaels',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav022',22,'Joe','Dillon','Midfield','Kingscourt',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav023',23,'Paul','OConnor','Forward','Cavan Gaels',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav024',24,'Cian','Mackey','Forward','Castlerahan',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav025',25,'Niall','McDermott','Forward','Ballinagh',0,0,0,0,0,0 );
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'cav026',26,'John','McCutcheon','Forward','Cootehill Celtic',0,0,0,0,0,0 );

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ( 'dub001',1,'Stephen','Cluxton','Goalkeeper','Parnells',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub002',2,'Philip','McMahon','Defender','Ballymun Kickhams',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub003',3,'Michael','Fitzsimons','Defender','Cuala',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub004',4,'David','Byrne','Defender','Naomh Ólaf',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub005',5,'Darren','Daly','Defender','Fingal Ravens',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub006',6,'John','Small','Defender','Ballymun Kickhams',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub007',7,'Eric','Lowndes','Defender','St. Peregrines',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub008',8,'Brian','Fenton','Midfield','Raheny',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub009',9,'Michael','Darragh','MacAuley','Midfield','Ballyboden St. Endas',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub010',10,'Niall','Scully','Forward','Templeogue Synge Street',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub011',11,'Dean','Rock','Forward','Ballymun Kickhams',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub012',12,'Shane','Carthy','Forward','St Vincents',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub013',13,'Ciarán','Kilkenny','Forward','Castleknock',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub014',14,'Eoghan','OGara','Forward','Templeogue Synge Street',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub015',15,'Conor','McHugh','Forward','Na Fianna',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub016',16,'Evan','Comerford','Goalkeeper','Ballymun Kickhams',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub017',17,'Colm','Basquel','Defender','Ballyboden St. Endas',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub018',18,'Shane','Carthy','Defender','Naomh Mearnóg',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub019',19,'Paul','Flynn','Defender','Fingallians',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub020',20,'Robbie','McDaid','Defender','Ballyboden St. Endas',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub021',21,'Kevin','McManamon','Midfield','St Judes',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub022',22,'Conor','Mullally','Midfield','Cuala',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub023',23,'Eoin','OBrien','Forward','Castleknock',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub024',24,'Emmett','ÓConghaile','Forward','Lucan Sarsfields',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub025',25,'Ciarán','Reddin','Forward','Naomh Maur',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('dub026',26,'Jack','Smith','Forward','Skerries Harps',0,0,0,0,0,0);

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker001',1,'Brendan','Kealy','Goalkeeper','Kilcummin',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker002',2,'Shane','Enright','Defender','Tarbert',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker003',3,'Killian','Young','Defender','Renard',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker004',4,'Ronan','Shanahan','Defender','Austin','Stacks',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker005',5,'Peter','Crowley','Defender','Laune Rangers',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker006',6,'Tadhg','Morley','Defender','Templenoe',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker007',7,'Paul','Murphy','Defender','Rathmore',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker008',8,'David','Moran','Midfield','Kerins ORahillys',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker009',9,'Jack','Barry','Midfield','Na Gaeil',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker010',10,'Kevin','McCarthy','Forward','Kilcummin',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker011',11,'Jack','Savage','Forward','Kerins ORahillys',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker012',12,'Donnchadh','Walsh','Forward','Cromane',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker013',13,'Barry','John Keane','Forward','Kerins ORahillys',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker014',14,'Paul','Geaney','Forward','Dingle',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker015',15,'James','ODonoghue','Forward','Legion',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker016',16,'Brian','Kelly','Goalkeeper','Legion',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker017',17,'Jonathan','Lyne','Defender','Legion',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker018',18,'Mark','Griffin','Defender','St. Michaels Foilmore',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker019',19,'Anthony','Maher','Defender','Duagh',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker020',20,'Stephen','OBrien','Defender','Kenmare Shamrocks',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker021',21,'Darran','OSullivan','Midfield','Glenbeigh Glencar',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker022',22,'Michael','Geaney','Midfield','Dingle',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker023',23,'Cathal','ÓLúing','Forward','An Ghaeltacht',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker024',24,'Gavin','Crowley','Forward','Templenoe',0,0,0,0,0,);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker025',25,'Denis','Daly','Forward','St. Marys',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ker026',26,'Conor','Keane','Forward','Legion',0,0,0,0,0,0);

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may001',1,'David','Clarke','Goalkeeper','Ballina Stephenites',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may002',2,'Donie','Newcombe','Defender','Castlebar Mitchels',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may003',3,'Keith','Higgins','Defender','Ballyhaunis',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may004',4,'Patrick','Durcan','Defender','Castlebar Mitchels',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may005',5,'Colm','Boyle','Defender','Davitts',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may006',6,'Stephen','Coen','Defender','Hollymount Carramore',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may007',7,'David','Drake','Defender','Ballaghadereen',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may008',8,'Donal','Vaughan','Midfield','Ballinrobe',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may009',9,'Jason','Gibbons','Midfield','Ballintubber',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may010',10,'Fergal','Boland','Forward','Aghamore',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may011',11,'Kevin','McLoughlin','Forward','Knockmore',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may012',12,'Diarmuid','OConnor','Forward','Ballintubber',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may013',13,'Evan','Regan','Forward','Ballina Stephenites',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may014',14,'Cillian','OConnor','Forward','Ballintubber',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may015',15,'Andy','Moran','Forward','Ballaghadereen',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may016',16,'Rob','Hennelly','Goalkeeper','Breaffy',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may017',17,'Brendan','Harrison','Defender','Aghamore',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may018',18,'Caolán','Crowe','Defender','Garrymore',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may019',19,'Michael','Plunkett','Defender','Ballintubber',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may020',20,'Eoghan','OReilly','Defender','Castlebar Mitchels',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may021',21,'Lee','Keegan','Midfield','Westport',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may022',22,'Shane','Nally','Midfield','Garrymore',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may023',23,'Conor','Loftus','Forward','Crossmolina Deel Rovers',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may024',24,'Conor','OShea','Forward','Breaffy',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may025',25,'Liam','Irwin','Forward','Breaffy',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('may026',26,'Tom','Parsons','Forward','Charlestown Sarsfields',0,0,0,0,0);

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr001',1,'Michael','ONeill','Goalkeeper','Clonoe',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr002',2,'Pádraig','Hampsey','Defender','Coalisland',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr003',3,'Ronan','McNamee','Defender','Aghyaran',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr004',4,'Cathal','McCarron','Defender','Dromore',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr005',5,'Tiernan','McCann','Defender','Killyclogher',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr006',6,'Mattie','Donnelly','Defender','Trillick',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr007',7,'Jonathan','Monroe','Defender','Carrickmore',0,0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr008',8,'Colm','Cavanagh','Midfield','Moy',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr009',9,'Pádraig','McNulty','Midfield','Dungannon',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr010',10,'Conor','Meyler','Forward','Omagh',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr011',11,'Niall','Sludden','Forward','Dromore',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr012',12,'Peter','Harte','Forward','Errigal Ciarán',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr013',13,'Darren','McCurry','Forward','Edendork',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr014',14,'Cathal','McShane','Forward','Owen Roe ONeills',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr015',15,'Ronan','ONeill','Forward','Omagh',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr016',16,'Niall','Morgan','Goalkeeper','Edendork',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr017',17,'Mark','Bradley','Defender','Killyclogher',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr018',18,'Lee','Brennan','Defender','Trillick',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr019',19,'Seán','Cavanagh','Defender','Moy',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr020',20,'Conall','McCann','Defender','Killyclogher',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr021',21,'Declan','McClure','Midfield','Clonoe',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr022',22,'Cahir','McCullagh','Midfield','Greencastle',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr023',23,'Aidan','McCrory','Forward','Errigal Ciarán',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr024',24,'Ronan','McHugh','Forward','Aghyaran',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr025',25,'Justin','McMahon','Forward','Omagh',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('tyr026',26,'David','Mulgrew','Forward','Ardboe',0,0,0,0,0);

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don001',1,'Mark Anthony','McGinley','Goalkeeper','St. Michaels',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don002',2,'Paddy','McGrath','Defender','Ardara',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don003',3,'Neil','McGee','Defender','Ghaoth Dobhair',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don004',4,'Eamon','McGee','Defender','Ghaoth Dobhair',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don005',5,'Ryan','McHugh','Defender','Kilcar',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don006',6,'Karl','Lacey','Defender','The Four Masters',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don007',7,'Frank','McGlynn','Defender','Glenfin',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don008',8,'Rory','Kavanagh','Midfield','St. Eunans',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don009',9,'Odhrán','MacNiallais','Midfield','Ghaoth Dobhair',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don010',10,'Anthony','Thompson','Forward','Naomh Conaill',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don011',11,'Martin','McElhinney','Forward','St. Michaels',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don012',12,'Eoin','McHugh','Forward','Kilcar',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don013',13,'Patrick','McBrearty','Forward','Kilcar',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don014',14,'Michael','Murphy','Forward','Glenswilly',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don015',15,'Martin','OReilly','Forward','Seán MacCumhaills',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don016',16,'Peter','Boyle','Goalkeeper','Aodh Ruadh',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don017',17,'Ciarán','Gillespie','Defender','Ghaoth Dobhair',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don018',18,'Leo','McLoone','Defender','Naomh Conaill',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don019',19,'Christy','Toye','Defender','St. Michaels',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don020',20,'Colm','McFadden','Defender','St. Michaels',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don021',21,'Hugh','McFadden','Midfield','Killybegs',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don022',22,'Mark','McHugh','Midfield','Kilcar',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don023',23,'Eamonn','Doherty','Forward','St. Eunans',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don024',24,'Ciarán','Thompson','Forward','Naomh Conaill',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don025',25,'Eoghan','Bán Gallagher','Forward','Killybegs',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('don026',26,'Michael','Carroll','Forward','Ghaoth Dobhair',0,0,0,0,0);

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon001',1,'Rory','Beggan','Goalkeeper','Scotstown',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon002',2,'Fintan','Kelly','Defender','Clones',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon003',3,'Drew','Wylie','Defender','Ballybay',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon004',4,'Ryan','Wylie','Defender','Ballybay',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon005',5,'Colin','Walshe','Defender','Doohamlet',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon006',6,'Neil','Mc Adam','Defender','Monaghan Harps',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon007',7,'Kieran','Duffy','Defender','Latton',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon008',8,'Darren','Hughes','Midfield','Scotstown',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon009',9,'Kieran','Hughes','Midfield','Scotstown',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon010',10,'Karl','OConnell','Forward','Tyholland',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon011',11,'Shane','Carey','Forward','Scotstown',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon012',12,'Gavin','Doogan','Forward','Magheracloone Mitchells',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon013',13,'Conor','McCarthy','Forward','Scotstown',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon014',14,'Thomas','Kerr','Forward','Ballybay',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon015',15,'Conor','McManus','Forward','Clontibret',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon016',16,'Conor','Forde','Goalkeeper','Scotstown',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon017',17,'James','Mealiff','Defender','Clones',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon018',18,'Owen','Coyle','Defender','Latton',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon019',19,'Brian','Greenan','Defender','Clontibret',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon020',20,'Mikey','Murnaghan','Defender','Donaghmoyne',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon021',21,'Niall','Kearns','Midfield','Sean McDermotts',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon022',22,'Dermot','Malone','Midfield','Castleblayney Faughs',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon023',23,'Owen','Duffy','Forward','Latton',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon024',24,'Ryan','McAnespie','Forward','Emyvale',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon025',25,'Stephen','Finnegan','Forward','Donaghmoyne',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('mon026',26,'Barry','McGinn','Forward','Doohamlet',0,0,0,0,0);

insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros001',1,'Darren','OMalley','Goalkeeper','Michael Glaveys',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros002',2,'David','Murray','Defender','Pádraig Pearses',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros003',3,'Seán','Mullooly','Defender','Strokestown',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros004',4,'Niall','McInerney','Defender','St. Brigids',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros005',5,'John','McManus','Defender','Roscommon Gaels',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros006',6,'Seán','McDermott','Defender','Western Gaels',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros007',7,'Conor','Devaney','Defender','Kilbride',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros008',8,'Enda','Smith','Midfield','Boyle',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros009',9,'Tadhg','ORourke','Midfield','Tulsk',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros010',10,'Fintan','Cregg','Forward','Elphin',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros011',11,'Ronan','Stack','Forward','St. Brigids',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros012',12,'Shane','Killoran','Forward','Elphin',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros013',13,'Donie','Smith','Forward','Boyle',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros014',14,'Ciaráin','Murtagh','Forward','St. Faithleachs',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros015',15,'Cian','Connolly','Forward','Roscommon Gaels',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros016',16,'Colm','Lavin','Goalkeeper','Éire Óg',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros017',17,'Paddy','Brogan','Defender','Strokestown',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros018',18,'Ciarán','Cafferkey','Defender','Western Gaels',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros019',19,'Thomas','Corcoran','Defender','Strokestown',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros020',20,'Thomas','Featherston','Defender','Oran',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros021',21,'Niall','Kilroy','Midfield','Fuerty',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros022',22,'Fergal','Lennon','Midfield','Clann na nGael',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros023',23,'Brian','Murtagh','Forward','St. Faithleachs',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros024',24,'Diarmuid','Murtagh','Forward','St. Faithleachs',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros025',25,'Gary','Patterson','Forward','Michael Glaveys',0,0,0,0,0);
insert into player(pid,num,fname,lname,pos,club,age,apps,points,yellows,blacks,reds) values ('ros026',26,'Brian','Stack','Forward','St. Brigids',0,0,0,0,0);
>>>>>>> origin/master
